env:
  SCRIPT: C:\\buildkite-agent\\builds\\RTC-DLLA48-1\\rtctek\\permission\\.buildkite\\test.sh
steps:

  - label: "Conditional Clean Before Init"
    commands: bash $SCRIPT conditional_clean

  - wait

  - label: "Setup"
    commands: bash $SCRIPT setup
  - wait

  - label: "init"
    key: "init"
    commands: bash $SCRIPT init
  - wait

  - label: "Run"
    key: "run"
    commands: bash $SCRIPT run
  - wait

  - label: "Clean"
    commands: bash $SCRIPT clean