env:
  SCRIPT: C:\buildkite-agent\builds\RTC-DLLA48-1\rtctek\permission\.buildkite\setup.sh
steps:
  - input: "Provide the users count"
    fields:
      - text: "Users count"
        key: "USERS"
        hint: "Number of concurrent users to simulate"
        default: "100"

  - input: "Provide the spawn rate"
    fields:
      - text: "Spawn Rate"
        key: "SPAWN_RATE"
        hint: "The rate at which users are spawned"
        default: "10"

  - input: "Provide the run time"
    fields:
      - text: "Run Time"
        key: "RUN_TIME"
        hint: "The total duration of the load test,Example values - 10m (10 minutes)"
        default: "10m"

  - label: "Check for changes in AWS directory"
    key: "check-changes"
    commands: bash $SCRIPT
    soft_fail: true

  - wait:
    
  - label: "Apply Terraform perf-use1-shared1"
    key: "apply"
    commands: |
      if [ $BUILDKITE_STEP_OUTCOME == "soft_failed" ]; then
        echo " no need to apply changes"
      else
        echo "need to"
      fi
    depends_on: "check-changes"
    
  - wait

  - label: "Deploy to perf-use1-shared1"
    commands: echo "deploy"
