env:
  SCRIPT: C:\\buildkite-agent\\builds\\RTC-DLLA48-1\\rtctek\\permission\\.buildkite\\test.sh
steps:
  - label: "Conditional Clean Before Init"
    commands: bash $SCRIPT conditional_clean

  - wait

  - label: "Initial Setup"
    commands: bash $SCRIPT setup
  - wait

  # - label: "Pre deployment"
  #   key: "init"
  #   commands: bash $SCRIPT init
  # - wait

  # - label: "Execute test cases"
  #   key: "run"
  #   commands: bash $SCRIPT run
  # - wait

  # - label: "Cleaning"
  #   commands: bash $SCRIPT clean