env:
  SCRIPT: C:\\buildkite-agent\\builds\\RTC-DLLA48-1\\rtctek\\permission\\.buildkite\\test.sh
steps:
  - label: "Conditional Clean Before Init"
    commands:
      - |
        if [ -d /pipeline_code_files ]; then 
          $PIPELINE_SCRIPT clean; 
        else 
          echo "Skipping clean step"; 
        fi
  - label: "Initial Setup"
    commands:
      - $SCRIPT setup
  - wait

  - label: "Pre deployment"
    key: "init"
    commands:
      - $SCRIPT init
  - wait

  - label: "Execute test cases"
    key: "run"
    commands:
      - $SCRIPT run
  - wait

  - label: "Cleaning"
    commands:
      - $SCRIPT clean