steps:
  - input: "Provide the users count"
    fields:
      - text: "Users count"
        key: "USERS"
        hint: "Number of concurrent users to simulate"

  - input: "Provide the spawn rate"
    fields:
      - text: "Spawn Rate"
        key: "SPAWN_RATE"
        hint: "The rate at which users are spawned"

  - input: "Provide the run time"
    fields:
      - text: "Run Time"
        key: "RUN_TIME"
        hint: "The total duration of the load test,Example values - 10m (10 minutes)"

  - label: "Check for changes in AWS directory"
    commands:
      - |
        CHANGED_FILES=$(git diff origin/main...HEAD --name-only | grep '.buildkite/slave/file/')
        if [[ -z "$CHANGED_FILES" ]]; then
          echo "Changes detected in AWS directory."
          export RUN_AWS_STEP=true
        else
          echo "No changes detected in AWS directory."
          unset RUN_AWS_STEP
        fi
  - label: "Apply Terraform perf-use1-shared1"
    commands:
      - echo "apply"
    if: build.env('RUN_AWS_STEP') == 'true'
